name: ✨ Feature request
description: Suggest an idea / 機能の要望
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like? / どんな機能がほしい？
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful? / どんな時に役立つ？
      description: What problem would it solve for you? / それがあると何が嬉しい？
